# Generated by Django 3.0.5 on 2020-04-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('password', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'login1',
            },
        ),
    ]
